<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>854764c8-f0a3-4740-a097-c5e9fb5e2a1f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShoppingCartService.Application\ShoppingCartService.Application.csproj" />
    <ProjectReference Include="..\ShoppingCartService.Domain\ShoppingCartService.Domain.csproj" />
    <ProjectReference Include="..\ShoppingCartService.Infrastructure\ShoppingCartService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
